---
##################
# Kolla defaults #
##################
host_ip: 10.100.100.1
kolla_node_internal_intf: ens4
kolla_node_external_intf: ens5
kolla_vm_os_distro: "{{ ansible_distribution | lower }}"
kolla_os_default_user: "{{ kolla_vm_os_distro }}"
pip_cache_enabled: "yes"
destroy_pip_cache: "no"
#apt_cache_enabled: "{{ 'yes' if kolla_vm_os_distro == 'ubuntu' else 'no' }}"
apt_cache_enabled: "no"
destroy_apt_cache: "no"
destroy_local_registry: "no"

# Path to Kolla configuration directory.
kolla_config_path: "{{ lookup('env', 'KOLLA_CONFIG_PATH') | default('/etc/kolla', true) }}"

########################
# Kolla build defaults #
########################
kolla_install_type: "source"
kolla_build_tag: "5.0.0"
kolla_image_namespace: "kolla-aio"
kolla_build_profile: "myprofile"
kolla_build_debug: true

############################
# Docker registry defaults #
############################
docker_registry_ip: "{{ host_ip }}"
docker_registry_port: 5000
pip_cache_proxy_ip: "{{ host_ip }}"
apt_cache_proxy_ip: "{{ host_ip }}"
