---
#####################
# Docker containers #
#####################
docker_registry_name: "registry"
docker_registry_image: "registry:2"

docker_pip_cache_name: "devpi_proxy"
docker_pip_cache_image: "127.0.0.1:5000/devpi"

docker_apt_cache_name: "apt-cacher-ng_proxy"
docker_apt_cache_image: "127.0.0.1:5000/apt-cacher-ng"

####################
# Host OS variables
####################
home_dir: "{{ ansible_user_dir }}"
tmp_dir: "{{ home_dir}}/tmp"
libvirt_dir: "/var/lib/libvirt/images"
host_interfaces:
  - name: prov-br
    role: prov
    cidr: 10.100.100.0/24
    bridge: prov-br
    vnic: ens3
  - name: mgmt-br
    role: mgmt
    cidr: 10.150.150.0/24
    bridge: mgmt-br
    vnic: ens4
  - name: ext-br
    role: ext
    cidr: 10.200.200.0/24
    bridge: ext-br
    vnic: ens5

yum_dependencies:
  - libvirt
  - libvirt-devel
  - bridge-utils
  - genisoimage
  - python-requests
  - qemu-kvm

apt_dependencies:
  - openssh-server
  - libvirt-bin
  - bridge-utils
  - genisoimage
  - python-requests
  - qemu-kvm

pip_dependencies:
  - docker
  - libvirt-python
  - lxml
  - pip

##################################
# Ubuntu/CentOS OS image variables
##################################
destroy_images: "no"
ubuntu_os_image_url: https://cloud-images.ubuntu.com/releases/16.04/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img
ubuntu_os_image: "{{ ubuntu_os_image_url.split('/')[-1] }}"
centos_os_image_xz_url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2.xz
centos_os_image_xz: "{{ centos_os_image_xz_url.split('/')[-1] }}"
centos_os_image: "{{ centos_os_image_xz.split('.')[:-1] | join('.') }}"

kolla_vm_os_image: "{{ centos_os_image if vm_os_distro == 'centos' else ubuntu_os_image }}"
os_default_user: "{{ vm_os_distro }}"

######################
# VMs variables
######################
cluster_nodes:
  - name: controller-1
    ram: 4096
    vcpu: 1
    role: controller-deploy
    interfaces:
      - name: "{{ host_interfaces | selectattr('role', 'equalto', 'prov') | map(attribute='vnic') | join }}"
        mode: dhcp
        role: prov
      - name: "{{ host_interfaces | selectattr('role', 'equalto', 'mgmt') | map(attribute='vnic') | join }}"
        mode: static
        address: "{{ host_interfaces | selectattr('role', 'equalto', 'mgmt') | map(attribute='cidr') | join | ipaddr('100') | ipaddr('address') }}"
        netmask: "{{ host_interfaces | selectattr('role', 'equalto', 'mgmt') | map(attribute='cidr') | join | ipaddr('netmask') }}"
        role: mgmt
      - name: "{{ host_interfaces | selectattr('role', 'equalto', 'ext') | map(attribute='vnic') | join }}"
        mode: static
        address: "{{ host_interfaces | selectattr('role', 'equalto', 'ext') | map(attribute='cidr') | join | ipaddr('100') | ipaddr('address') }}"
        netmask: "{{ host_interfaces | selectattr('role', 'equalto', 'ext') | map(attribute='cidr') | join | ipaddr('netmask') }}"
        role: ext
  - name: node-1
    ram: 4096
    vcpu: 1
    role: compute
    interfaces:
      - name: "{{ host_interfaces | selectattr('role', 'equalto', 'prov') | map(attribute='vnic') | join }}"
        mode: dhcp
        role: prov
      - name: "{{ host_interfaces | selectattr('role', 'equalto', 'mgmt') | map(attribute='vnic') | join }}"
        mode: static
        address: "{{ host_interfaces | selectattr('role', 'equalto', 'mgmt') | map(attribute='cidr') | join | ipaddr('101') | ipaddr('address') }}"
        netmask: "{{ host_interfaces | selectattr('role', 'equalto', 'mgmt') | map(attribute='cidr') | join | ipaddr('netmask') }}"
        role: mgmt
      - name: "{{ host_interfaces | selectattr('role', 'equalto', 'ext') | map(attribute='vnic') | join }}"
        mode: static
        address: "{{ host_interfaces | selectattr('role', 'equalto', 'ext') | map(attribute='cidr') | join | ipaddr('101') | ipaddr('address') }}"
        netmask: "{{ host_interfaces | selectattr('role', 'equalto', 'ext') | map(attribute='cidr') | join | ipaddr('netmask') }}"
        role: ext
  - name: node-2
    ram: 4096
    vcpu: 1
    role: compute
    interfaces:
      - name: "{{ host_interfaces | selectattr('role', 'equalto', 'prov') | map(attribute='vnic') | join }}"
        mode: dhcp
        role: prov
      - name: "{{ host_interfaces | selectattr('role', 'equalto', 'mgmt') | map(attribute='vnic') | join }}"
        mode: static
        address: "{{ host_interfaces | selectattr('role', 'equalto', 'mgmt') | map(attribute='cidr') | join | ipaddr('102') | ipaddr('address') }}"
        netmask: "{{ host_interfaces | selectattr('role', 'equalto', 'mgmt') | map(attribute='cidr') | join | ipaddr('netmask') }}"
        role: mgmt
      - name: "{{ host_interfaces | selectattr('role', 'equalto', 'ext') | map(attribute='vnic') | join }}"
        mode: static
        address: "{{ host_interfaces | selectattr('role', 'equalto', 'ext') | map(attribute='cidr') | join | ipaddr('102') | ipaddr('address') }}"
        netmask: "{{ host_interfaces | selectattr('role', 'equalto', 'ext') | map(attribute='cidr') | join | ipaddr('netmask') }}"
        role: ext
