---
####################
# Host OS variables
####################
node_prefix: ""

# Cluster sizing info
#####################
master_nb: 1
master_ram: 4
master_cpu: 1

worker_nb: 2
worker_ram: 4
worker_cpu: 1

# Networking info
#################
host_interfaces:
  - name: prov-br
    forward: nat
    mode: dhcp
    cidr: 10.100.100.0/24
    bridge: prov-br
  - name: mgmt-br
    mode: static
    cidr: 10.150.150.0/24
    bridge: mgmt-br
  # - name: br0-br
  #   forward: bridge
  #   mode: static
  #   cidr: 10.200.200.0/24
  #   bridge: br0
  # - name: ext-br
  #   cidr: 10.200.200.0/24
  #   bridge: ext-br

dns_domain: "mydomain.org"

# Storage info
##############
storage_volume_enabled: True
virt_volume_group: "virtvg"

host_volumes:
  - name: volume1
    size: 10
    format: raw
  - name: volume2
    size: 10
    format: raw
  - name: volume3
    size: 10
    format: raw
