---
#####################
# Docker containers #
#####################
docker_registry_name: "registry"
docker_registry_image: "registry:2"

docker_pip_cache_name: "devpi_proxy"
docker_pip_cache_image: "127.0.0.1:5000/devpi"

docker_apt_cache_name: "apt-cacher-ng_proxy"
docker_apt_cache_image: "127.0.0.1:5000/apt-cacher-ng"

docker_dns_server_name: "docker-dnsmasq"
docker_dns_server_image: "127.0.0.1:5000/docker-dnsmasq"

####################
# Host OS variables
####################
node_prefix: ""
home_dir: "{{ ansible_user_dir }}"
tmp_dir: "{{ home_dir}}/tmp"
libvirt_dir: "/var/lib/libvirt/images"
dns_domain: "mydomain.org"

master_nb: 1
master_ram: 4
master_cpu: 1

worker_nb: 2
worker_ram: 4
worker_cpu: 1

host_interfaces:
  - name: prov-br
    forward: nat
    mode: dhcp
    cidr: 10.100.100.0/24
    bridge: prov-br
  - name: mgmt-br
    mode: static
    cidr: 10.150.150.0/24
    bridge: mgmt-br
  # - name: br0-br
  #   forward: bridge
  #   mode: static
  #   cidr: 10.200.200.0/24
  #   bridge: br0

  # - name: ext-br
  #   cidr: 10.200.200.0/24
  #   bridge: ext-br

yum_dependencies:
  - libvirt
  - libvirt-devel
  - bridge-utils
  - genisoimage
  - python-requests
  - qemu-kvm

apt_dependencies:
  - openssh-server
  - libvirt-bin
  - bridge-utils
  - genisoimage
  - python-requests
  - qemu-kvm

pip_dependencies:
  - docker
  - libvirt-python
  - lxml
  - pip

##################################
# Ubuntu/CentOS OS image variables
##################################
destroy_images: "no"
ubuntu_os_image_url: https://cloud-images.ubuntu.com/releases/16.04/release/ubuntu-16.04-server-cloudimg-amd64-disk1.img
ubuntu_os_image: "{{ ubuntu_os_image_url.split('/')[-1] }}"
centos_os_image_xz_url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2.xz
centos_os_image_xz: "{{ centos_os_image_xz_url.split('/')[-1] }}"
centos_os_image: "{{ centos_os_image_xz.split('.')[:-1] | join('.') }}"

kolla_vm_os_image: "{{ centos_os_image if vm_os_distro == 'centos' else ubuntu_os_image }}"
os_default_user: "{{ vm_os_distro }}"
