---
- name: List storage pool
  virt_pool:
    command: list_pools
  register: pool_exists

- name: "Create {{ virt_volume_group }} storage pool"
  virt_pool:
    command: create
    name: "{{ virt_volume_group }}"
  when: virt_volume_group not in pool_exists.list_pools

- name: Create virtual volumes
  virt_volume:
    name: "{{ item.1.name }}"
    capacity: "{{ item.1.size }}G"
    pool: "{{ virt_volume_group }}"
    format: "{{ item.1.format | default('raw') }}"
    state: present
    # strategy: least
  with_subelements:
    - "{{ cluster_nodes }}"
    - disks
