---
- name: List virtual networks
  virt_net:
    command: list_nets
  register: net_exists

- name: Display cluster_nodes
  debug:
    msg: "{{ lookup('template','network.xml.j2') }}"
  when: item.name not in net_exists.list_nets
  with_items: "{{ host_interfaces }}"

- name: Define virtual networks
  virt_net:
    command: define
    name: "{{ item.name }}"
    xml: '{{ lookup("template", "network.xml.j2") }}'
  when: item.name not in net_exists.list_nets
  with_items: "{{ host_interfaces }}"

- name: Autostart virtual networks
  virt_net:
    autostart: yes
    name: "{{ item.name }}"
  when: item.name not in net_exists.list_nets
  with_items: "{{ host_interfaces }}"

- name: Start virtual networks
  virt_net:
    state: active
    autostart: yes
    name: "{{ item.name }}"
  when: item.name not in net_exists.list_nets
  with_items: "{{ host_interfaces }}"

# - name: Setup NetworkManager dnsmasq config file
#   lineinfile:
#     path: "/etc/NetworkManager/dnsmasq.d/libvirt_dnsmasq.conf"
#     create: yes
#     line: "server=/{{ item.domain }}/{{ item.cidr | join | ipaddr('1') | ipaddr('address') }}"
#   when: item.domain is defined
#   with_items: "{{ host_interfaces }}"
